[package]
name = "minecraft-ping"
version = "0.0.1"
edition = "2021"
rust-version = "1.70"

[dependencies]
base64 = "0.21.2"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"

[[bin]]
name = "mping"
path = "src/main.rs"
